== Kernel Installation

A kernel compiled for the host machine on which it is built can be installed
in the system by issuing a _make install_ after the build is successful. To
install the kernel image we would required root permissions.

The installation includes the following:

/boot/vmlinuz-<version>:: The compressed kernel image. This is copied from
the _arch/<ARCH>/boot_ directory.
/boot/System.map-<version>:: This file stores the kernel symbols along with
their addresses and will be handy in the event of a Kernel panic
/boot/config-<version>:: This is the configuration file _.config_ saved
along with the compiled kernel

The installation may also reconfigured the bootloader to take the new
kernel settings so that on the next boot the new kernel will be visible.

=== Kernel Module Installation

Along with the kernel the compiled modules will also have to be installed
in the system. To achieve this there is a target _modules_install_ which
can be executed after executing the _install_ target of the root makefile.

The kernel modules and related files are installed in the
_/lib/modules/<version>/_ directory. If we explore this directory we will
see the following:

kernel/:: This directory contains a directory structure similar to the
kernel source code. The kernel modules will be saved in the same directory
structure as the source from which they were built.
modules.alias:: Aliases for the modules for loading utilities. An example
of the contents of this file is given below:

[source,bash]
----
conrad@conrad-HP-Pavilion-dm3-Notebook-PC:~$ head /lib/modules/3.13.0-45-generic/modules.alias
# Aliases extracted from modules themselves.
alias char-major-10-134 apm
alias aes-asm aes_i586
alias aes aes_i586
alias twofish-asm twofish_i586
alias twofish twofish_i586
alias salsa20-asm salsa20_i586
alias salsa20 salsa20_i586
alias serpent serpent_sse2_i586
alias aes aesni_intel
----

modules.dep:: Highlights the dependencies between modules. This will be used by
_modprobe_ to choose which kernel modules have to be loaded before loading a
particular module. In the example below mce_inject.ko has no dependency and can
be loaded without any issue. But twofish-i586.ko depends on twofish_common.ko
which must be loaded first.

[source,bash]
----
conrad@conrad-HP-Pavilion-dm3-Notebook-PC:~$ head /lib/modules/3.13.0-45-generic/modules.dep
kernel/arch/x86/kernel/cpu/mcheck/mce-inject.ko:
kernel/arch/x86/kernel/msr.ko:
kernel/arch/x86/kernel/cpuid.ko:
kernel/arch/x86/kernel/apm.ko:
kernel/arch/x86/crypto/glue_helper.ko:
kernel/arch/x86/crypto/aes-i586.ko:
kernel/arch/x86/crypto/twofish-i586.ko: kernel/crypto/twofish_common.ko
kernel/arch/x86/crypto/salsa20-i586.ko:
kernel/arch/x86/crypto/serpent-sse2-i586.ko: kernel/crypto/xts.ko kernel/crypto/serpent_generic.ko kernel/crypto/lrw.ko kernel/crypto/gf128mul.ko kernel/arch/x86/crypto/glue_helper.ko kernel/crypto/ablk_helper.ko kernel/crypto/cryptd.ko
kernel/arch/x86/crypto/aesni-intel.ko: kernel/arch/x86/crypto/aes-i586.ko kernel/crypto/xts.ko kernel/crypto/lrw.ko kernel/crypto/gf128mul.ko kernel/crypto/ablk_helper.ko kernel/crypto/cryptd.ko
----

modules.symbols:: Describes the kernel module to which a symbol belongs. It can
be useful during debugging of a Kernel panic. For example we can see that
cfg80211_report_obss_beacon belongs to the cfg80211 kernel module.

[source,bash]
----
conrad@conrad-HP-Pavilion-dm3-Notebook-PC:~$ head /lib/modules/3.13.0-45-generic/modules.symbols
# Aliases for symbols, used by symbol_request().
alias symbol:cfg80211_report_obss_beacon cfg80211
alias symbol:drm_dp_link_train_channel_eq_delay drm_kms_helper
alias symbol:VBoxHost_RTThreadPreemptDisable vboxdrv
alias symbol:__twofish_setkey twofish_common
alias symbol:get_wd_exp_mode_sd bpctl_mod
alias symbol:hsi_register_controller hsi
alias symbol:mlx4_db_free mlx4_core
alias symbol:sdhci_remove_host sdhci
alias symbol:videobuf_dma_init_kernel videobuf_dma_sg
----

=== Cleaning Up

There are several targets that are used to clean up files that have been
generated by the configuration and compilation of the Linux kernel source
code.

make clean:: This will remove all the generated object code files to allow
us to rebuilt the kernel.

make mrproper:: Remove all the generated files including the configuration
file _.config_. It may be used if we are rebuilding the kernel source
code for a different architecture.

make distclean:: This target is used to remove editor backup files. It is
mainly used when generating patches.
