:uri-libusb-org: http://www.libusb.org/
:uri-kernel-org-spidev-doc: https://www.kernel.org/doc/Documentation/spi/spidev
:uri-kernel-org-i2cdev-doc: https://www.kernel.org/doc/Documentation/i2c/dev-interface
:uri-free-electrons-uio-howto: http://free-electrons.com/kerneldoc/latest/DocBook/uio-howto/

== User Space Device Drivers

It is possible to develop a user space device driver. There are several 
scenarios in which a user space device driver is developed:

. The device driver does not depend on any of the frameworks exposed by
the Linux Kernel.

. The device driver is used by only one application and is not required
by any other application.

. The kernel provides a simple interface with which the user space device
driver can control and read the hardware for which it is developed.

=== Examples Of User Space Device Drivers

Certain busses have interfaces exposed by the kernel which can be used to
develop a user space device driver if the hardware is connected to that 
bus:

. USB with libusb, {uri-libusb-org}[{uri-libusb-org}^]
. SPI wiht spidev, {uri-kernel-org-spidev-doc}[Documentation/spi/spidev^] 
. I2C with i2cdev, {uri-kernel-org-i2cdev-doc}[Documentation/i2c/dev-interface^]
. Memory-mapped devices with UIO, including interrupt handling, {uri-free-electrons-uio-howto}[{uri-free-electrons-uio-howto}^]

On certain SOCs the vendor also provides a user space device driver along with
a kernel driver which has access to other processors in the SOC which are
running a firmware for highly specialized applications.

=== The Good And The Bad Of User Space Device Drivers

The Good

. The driver can be written in any programming language or script.
. The driver can be kept proprietary.
. The driver runs in user space as an application or daemon.
. The driver cannot bring down the kernel.

The Bad

. Handling interrupts from the hardware is non-trivial resulting in some sort
of polling mechanism.
. The interrupt latency is larger when compared to a kernel device driver.
