// rvm use 2.1@runtime
// asciidoctor -D /tmp/ -a data-uri -a stem user-manual.adoc
= Exploring Embedded Linux With The BeagleBone Black
Conrad Gomes <conrad.s.j.gomes@gmail.com>
:description: This is a journal of my experience with BeagleBone Black
:keywords: BeagleBone Black
:doctype: book
:compat-mode:
//:page-layout!:
:page-layout: base
:toc: left
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:
:linkattrs:
:icons: font
:source-highlighter: coderay
:source-language: asciidoc
:experimental:
:stem:
:idprefix:
:idseparator: -
:ast: &ast;
:dagger: pass:normal[^&dagger;^]
:y: icon:check[role="green"]
:n: icon:times[role="red"]
:c: icon:file-text-o[role="blue"]
:table-caption!:
:example-caption!:
:figure-caption!:
:imagesdir: ../images
:includedir: _includes
:underscore: _
// Refs
:uri-conrad-mail: mailto:conrad.s.j.gomes@gmail.com
:uri-free-electrons: http://free-electrons.com/

:compat-mode!:

toc::[]


[NOTE]
.This document is under active development!
====
If you find errors or omissions in this document, please don't hesitate to {uri-conrad-mail}[send me a mail].
====

This manual assumes you are comfortable with a linux environment as most of the
published work here uses an Ubuntu distribution as the work station.


= Introduction

[partintro]
--
{uri-free-electrons}[Free Electrons^] is an engineering company consisting of
embedded linux experts who support companies using Embedded Linux. They 
additionally conduct training workshops for companies on different topics 
such as Linux kernel and device driver development, Android system development, 
Yocto Project and OpenEmbedded development, etc. This manual uses the Free 
Electrons training material which they publish online to explore Embedded Linux
with the BeagleBone Black board from TI.
--

== About BeagleBoard

== BeagleBoard References

= Workstation Setup

[partintro]
--
NOTE: Section Pending
--
