name: TechEuphoria
title: A Technical Odyssey
org: conrad.s.j.gomes@gmail.com
author: Conrad Gomes
base_url: http://zeuzoix.github.io/techeuphoria/
#interpolate: false
haml:
  :ugly: true
asciidoctor:
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
profiles:
  development:
    deploy: nil
  staging:
    deploy: nil
  production:
    base_url: http://zeuzoix.github.io/techeuphoria/
#   ctx-path: /techeuphoria
#   asciidoctor:
#     :attributes:
#     base_url: http://zeuzoix.github.io/techeuphoria/
#     ctx_path: /techeuphoria
    deploy:
      host: github_pages
      branch: gh-pages
