name: TechEuphoria
title: A Technical Odyssey
org: conrad.s.j.gomes@gmail.com
author: Conrad Gomes
base_url: ''
interpolate: false
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: TechEuphoria
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://zeuzoix.github.io/techeuphoria
    ctx-path: /techeuphoria
    asciidoctor:
      :attributes:
        base_url: http://zeuzoix.github.io/techeuphoria
        ctx_path: /techeuphoria
        # imagesdir must be absolute to work around Atom feed bug
        imagesdir: http://zeuzoix.github.io/techeuphoria/images
    deploy:
      host: github_pages
      branch: gh-pages
