= iFanaticism
Conrad Gomes
2011-10-16
:awestruct-tags: [design]
:excerpt: It's amazing, I'm going through the news paper and I read about people in Tokyo who've queued outside an Apple store to buy the iPhone 4s in memory of the late Steve Jobs.
:awestruct-excerpt: {excerpt}

{excerpt}

What was it about Steve Jobs that moves people not in his own country but in
countries other than his own? What was it about him that caused millions to
pour out their hearts on twitter and facebook when they heard of his death.
Steve Jobs has been catapulted to the status of a rock-star. No other
entrepreneur has ever had the admiration and adoration of millions of
people. It's pure fanaticism!

His products have been sought after by many fans. People literally stand in
queues to pick up Apple's products. They want the real deal. People don't buy
cheaper imitations from China. They find value for money in those gadgets.
Enough to convert them into evangelists for Apple.
 
Steve Jobs now shares his place with those that inspired and evoked euphoria
in the millions. People like Curt Cobain, Elvis Presley and Michael Jackson.
He redefined product conceptualization. But there's a question that comes to
my mind. Steve's best was at the end of his life. Was it his awareness of his
condition that pushed him to create the best products of Apple?

Whatever it was one thing's for sure, he's made a dent in the universe. 

